--Randyll Bearer & Zachary White
--CS 1555 Project
--Milestone 1: Database Schema

--Sample Insert Data for Project 1

--MUTUALDATE
INSERT INTO MUTUALDATE(c_date) 
	VALUES (TO_DATE ('04-APR-14', 'DD-MON-YY') );

--CUSTOMER
INSERT INTO CUSTOMER(login, name, email, address, password, balance)
	VALUES ('mike', 'Mike', 'mike@betterfuture.com', '1st street', 'pwd', 750);
INSERT INTO CUSTOMER VALUES ('mary', 'Mary', 'mary@betterfuture.com', '2st street', 'pwd', '0');

--ADMINISTRATOR
INSERT INTO ADMINISTRATOR(login, name, email, address, password)
	VALUES('admin', 'Administrator', 'admin@betterfuture.com', '5th Ave, Pitt', 'root');

--MUTUALFUND
INSERT INTO MUTUALFUND(symbol, name, description, category, c_date)
	VALUES('MM', 'money-market', 'money market, conservative', 'fixed', TO_DATE('06-JAN-14', 'DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('RE', 'real-estate', 'real estate', 'fixed', TO_DATE('09-JAN-14', 'DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('STB', 'short-term-bonds', 'short term bonds', 'bonds', TO_DATE('10-JAN-14', 'DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('LTB', 'long-term-bonds', 'long term bonds', 'bonds', TO_DATE('11-JAN-14', 'DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('BBS', 'balance-bonds-stocks', 'balance bonds and stocks', 'mixed', TO_DATE('12-JAN-14','DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('SRBS', 'social-respons-bonds-stocks', 'social responsibility bonds and stocks', 'mixed', TO_DATE('12-JAN-14','DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('GS', 'general-stocks', 'general stocks', 'stocks', TO_DATE('16-JAN-14','DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('AS', 'aggressive-stocks', 'aggressive stocks', 'stocks', TO_DATE('23-JAN-14','DD-MON-YY') );
INSERT INTO MUTUALFUND VALUES('IMS', 'international-markets-stock', 'international markets stock, risky', 'stocks', TO_DATE('30-JAN-14','DD-MON-YY') );

--OWNS
INSERT INTO OWNS(login, symbol, shares)
	VALUES('mike', 'RE', 50);

--ALLOCATION
INSERT INTO ALLOCATION(allocation_no, login, p_date)
	VALUES(0, 'mike', TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO ALLOCATION VALUES(1, 'mary', TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO ALLOCATION VALUES(2, 'mike', TO_DATE('03-APR-14','DD-MON-YY') );

--PREFERS
INSERT INTO PREFERS(allocation_no, symbol, percentage)
	VALUES(0, 'MM', .5);
INSERT INTO PREFERS VALUES(0, 'RE', .5);
INSERT INTO PREFERS VALUES(1, 'STB', .2);
INSERT INTO PREFERS VALUES(1, 'LTB', .4);
INSERT INTO PREFERS VALUES(1, 'BBS', .4);
INSERT INTO PREFERS VALUES(2, 'GS', .3);
INSERT INTO PREFERS VALUES(2, 'AS', .3);
INSERT INTO PREFERS VALUES(2, 'IMS', .4);

--CLOSINGPRICE
INSERT INTO CLOSINGPRICE(symbol, price, p_date)
	VALUES('MM', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('MM', 11, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('MM', 12, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('MM', 15, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('MM', 14, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('MM', 15, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('MM', 16, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 12, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 15, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 14, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 16, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 17, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('RE', 15, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 9, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 10, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 12, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 14, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 10, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('STB', 12, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 12, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 13, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 15, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 12, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 9, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('LTB', 10, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 11, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 14, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 18, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 13, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 15, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('BBS', 16, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 12, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 12, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 14, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 17, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 20, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('SRBS', 20, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 12, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 13, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 15, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 14, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 15, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('GS', 12, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 15, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 14, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 16, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 14, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 17, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('AS', 18, TO_DATE('03-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 10, TO_DATE('28-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 12, TO_DATE('29-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 12, TO_DATE('30-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 14, TO_DATE('31-MAR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 13, TO_DATE('01-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 12, TO_DATE('02-APR-14','DD-MON-YY') );
INSERT INTO CLOSINGPRICE VALUES('IMS', 11, TO_DATE('03-APR-14','DD-MON-YY') );

--TRXLOG
--This deposit triggers onInsert_trxlog_deposit, which creates 2 buy transactions
INSERT INTO TRXLOG(trans_id, login, symbol, t_date, action, num_shares, price, amount)
	VALUES(0, 'mike', 'MM', TO_DATE('29-MAR-14','DD-MON-YY'), 'deposit', NULL, NULL, 1000 );
--Added Mary deposit to test trigger.
INSERT INTO TRXLOG(trans_id, login, symbol, t_date, action, num_shares, price, amount)
	VALUES(4, 'mary', 'MM', TO_DATE('29-MAR-14','DD-MON-YY'), 'deposit', NULL, NULL, 1000 );
--Sell automatically removes the 0 shares record from owns table via trigger
INSERT INTO TRXLOG VALUES(8, 'mike', 'RE', TO_DATE('01-APR-14','DD-MON-YY'), 'sell', 50, 15, 750 );
commit;	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	